//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurBuroDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ИнформацияКлиента
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ИнформацияКлиента()
        {
            this.Тур = new HashSet<Тур>();
        }
    
        public int КодКлиента { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public Nullable<System.DateTime> ДатаРождения { get; set; }
        public int КодПола { get; set; }
    
        public virtual Пол Пол { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Тур> Тур { get; set; }
    }
}
