//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurBuroDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь
    {
        public int КодПользователя { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string Пол { get; set; }
        public string Логин { get; set; }
        public int Пароль { get; set; }
        public int КодРоли { get; set; }
        public int КодДолжности { get; set; }
    
        public virtual Должность Должность { get; set; }
        public virtual Роли Роли { get; set; }
        public virtual Фото Фото { get; set; }
    }
}
