//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurBuroDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тур
    {
        public int КодТура { get; set; }
        public string Название { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public int КодСтраны { get; set; }
        public int КодВидТура { get; set; }
        public int КодПитания { get; set; }
        public int КодПроживания { get; set; }
        public Nullable<int> КодКлиента { get; set; }
    
        public virtual ВидТура ВидТура { get; set; }
        public virtual ИнформацияКлиента ИнформацияКлиента { get; set; }
        public virtual Питание Питание { get; set; }
        public virtual Проживание Проживание { get; set; }
        public virtual Страны Страны { get; set; }
    }
}
